- hosts: all
  become: true
  become_user: ubuntu

  tasks:
    # Upgrade packages
    - name: upgrade apt packages
      become: true
      become_user: ubuntu
      apt:
        upgrade: yes
        update_cache: yes

    # Check if reboot is required
    - name: check if system reboot is required
      become: true
      become_user: ubuntu
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: curl ntfy
      ansible.builtin.shell: 
        cmd: "curl -u {{ PASSWORD }} -d '' -H 'Title: Reboot required on {{ inventory_hostname }}' -H 'Tags: floppy_disk' {{ SERVER }}"
      #when: reboot_required.stat.exists

