- hosts: all

  become: yes
  tasks:
    # # Upgrade packages
    # - name: upgrade apt packages
    #   become: true
    #   apt:
    #     upgrade: yes
    #     update_cache: yes

    # # Check if reboot is required
    # - name: check if system reboot is required
    #   become: true
    #   stat:
    #     path: /var/run/reboot-required
    #   register: reboot_required

    - name: Use curl to fetch a webpage
      ansible.builtin.shell: 
        cmd: 'curl \
              -u {{ lookup("env", "PASSWORD") }} \
              -d "Hello" \
              -H "Title: RClone Backup of Immich to s3 completed" \
              -H "Tags: floppy_disk" \
              {{ lookup("env", "SERVER") }}'
      register: result

