- name: Run backup script
  hosts: "{{ HOST }}"
  tasks:
    - name: Run backup script
      shell: |
        rm -f /root/rclone-logs/logs.txt

        rclone sync /mnt/pve/truenas-backups/dump/ hetzner_crypt:main/proxmox --log-file /root/rclone-logs/logs.txt --stats-log-level NOTICE

        backup_log=$(cat /root/rclone-logs/logs.txt)

        curl \
        -u {{ PASSWORD }} \
        -d "$backup_log" \
        -H "Title: Proxmox backups sync completed" \
        -H "Tags: floppy_disk" \
        {{ SERVER }}
